# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ea0a394c6b9fdbcc94da5e70d48ed7915f337f4bff203c28d92109331e0871332e9e0b6d05f202001025752254d23353d2c65addd477efbc259fbda6b9cb8f

test:
  secret_key_base: c359cdd8dd5c80d59d36762f4d16221898c1dd2eee19a3d677f2350263429319857ec43c82bd307fb06b42a6cd54d1a4eace4febb3a1efc8df0477b37efa741c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
